// Command layoutgen writes layouts.go: for every non-Latin xkb layout on this machine, the rune
// each key gives, mapped back to the US key in the same place. Run from internal/tui:
//
//	go run ./layoutgen > layouts.go && gofmt -w layouts.go
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

const xkb = "/usr/share/X11/xkb/symbols"

var us = map[string][2]rune{}

func init() {
	rows := []struct{ prefix, lo, hi string }{
		{"AE", "1234567890-=", "!@#$%^&*()_+"},
		{"AD", "qwertyuiop[]", "QWERTYUIOP{}"},
		{"AC", "asdfghjkl;'", "ASDFGHJKL:\""},
		{"AB", "zxcvbnm,./", "ZXCVBNM<>?"},
	}
	for _, r := range rows {
		lo, hi := []rune(r.lo), []rune(r.hi)
		for i := range lo {
			us[fmt.Sprintf("%s%02d", r.prefix, i+1)] = [2]rune{lo[i], hi[i]}
		}
	}
	us["TLDE"] = [2]rune{'`', '~'}
	us["BKSL"] = [2]rune{'\\', '|'}
}

// the layouts people most likely type in win a rune that two layouts put on different keys
var first = []string{"ir", "ara", "ru", "ua", "by", "bg", "il", "gr", "th", "am", "ge", "kz", "mk", "rs", "mn", "tj", "af", "pk", "in", "kr", "jp"}

func main() {
	syms := keysyms()
	files, _ := os.ReadDir(xkb)
	order := append([]string{}, first...)
	for _, f := range files {
		if !f.IsDir() && !contains(first, f.Name()) {
			order = append(order, f.Name())
		}
	}
	to := map[rune]rune{}
	var used []string
	for _, name := range order {
		keys := map[string][]string{}
		if !load(name, "", keys, 0) {
			continue
		}
		names := make([]string, 0, len(keys))
		for k := range keys {
			if _, ok := us[k]; ok && len(keys[k]) > 0 {
				names = append(names, k)
			}
		}
		sort.Strings(names)
		layer := map[rune]rune{}
		// a shifted letter goes to the key whose plain level is its lower case (Σ to s, not to ς's w)
		for pass := 0; pass < 3; pass++ {
			for _, k := range names {
				levels, pos := keys[k], us[k]
				l := map[bool]int{true: 0, false: 1}[pass == 1]
				if l >= len(levels) {
					continue
				}
				r, ok := syms[levels[l]]
				if !ok || r < 0x80 {
					continue
				}
				low := syms[levels[0]]
				if pass == 0 && unicode.ToLower(r) != low || pass == 0 && r == low {
					continue
				}
				if _, dup := layer[r]; !dup {
					layer[r] = pos[l]
				}
			}
		}
		letters, foreign := 0, 0
		for _, k := range names {
			if k[:2] == "AD" || k[:2] == "AC" || k[:2] == "AB" {
				letters++
				if r, ok := syms[keys[k][0]]; ok && r >= 0x80 {
					foreign++
				}
			}
		}
		if letters == 0 || foreign*2 < letters {
			continue // a Latin layout: its letters already are the keys
		}
		used = append(used, name)
		for r, k := range layer {
			if _, taken := to[r]; !taken {
				to[r] = k
			}
		}
	}
	runes := make([]rune, 0, len(to))
	for r := range to {
		runes = append(runes, r)
	}
	sort.Slice(runes, func(i, j int) bool { return runes[i] < runes[j] })
	fmt.Println("// Code generated by layoutgen from xkb (" + strings.Join(used, " ") + "); DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package tui")
	fmt.Println()
	fmt.Println("// layoutKeys pairs each rune a non-Latin keyboard layout types with the US key in its place.")
	fmt.Println("var layoutKeys = map[rune]rune{")
	for _, r := range runes {
		fmt.Printf("\t%s: %s,\n", strconv.QuoteRune(r), strconv.QuoteRune(to[r]))
	}
	fmt.Println("}")
}

var (
	variantRe = regexp.MustCompile(`((?:[a-z_]+\s+)*)xkb_symbols\s+"([^"]+)"\s*\{`)
	includeRe = regexp.MustCompile(`^\s*include\s+"([^"(]+)(?:\(([^)]+)\))?"`)
	keyRe     = regexp.MustCompile(`^\s*key\s+<(\w+)>\s*\{(.*)`)
	levelsRe  = regexp.MustCompile(`\[([^\]]*)\]`)
)

// load reads one variant (the default one when variant is empty) with its includes into keys
func load(file, variant string, keys map[string][]string, depth int) bool {
	if depth > 8 {
		return false
	}
	data, err := os.ReadFile(filepath.Join(xkb, file))
	if err != nil {
		return false
	}
	text := string(data)
	locs := variantRe.FindAllStringSubmatchIndex(text, -1)
	start := -1
	for i, l := range locs {
		flags, name := text[l[2]:l[3]], text[l[4]:l[5]]
		if (variant == "" && (strings.Contains(flags, "default") || i == 0 && start < 0)) || name == variant {
			start = l[1]
			if variant != "" || strings.Contains(flags, "default") {
				break
			}
		}
	}
	if start < 0 {
		return false
	}
	depthBraces := 1
	sc := bufio.NewScanner(strings.NewReader(text[start:]))
	for sc.Scan() && depthBraces > 0 {
		line := sc.Text()
		if i := strings.Index(line, "//"); i >= 0 {
			line = line[:i]
		}
		if m := includeRe.FindStringSubmatch(line); m != nil {
			load(m[1], m[2], keys, depth+1)
		} else if m := keyRe.FindStringSubmatch(line); m != nil {
			body := m[2]
			if s := strings.Index(body, "symbols[Group1]"); s >= 0 {
				body = body[s:]
			}
			if lv := levelsRe.FindStringSubmatch(body); lv != nil {
				levels := keys[m[1]]
				for i, f := range strings.Split(lv[1], ",") {
					if f = strings.TrimSpace(f); f == "NoSymbol" || f == "any" || f == "" {
						continue // an include adding a level keeps the ones below it
					}
					for len(levels) <= i {
						levels = append(levels, "")
					}
					levels[i] = f
				}
				keys[m[1]] = levels
			}
		}
		depthBraces += strings.Count(line, "{") - strings.Count(line, "}")
	}
	return true
}

var symRe = regexp.MustCompile(`^#define XK_(\w+)\s+0x[0-9a-fA-F]+\s*/\*[ (]*U\+([0-9A-Fa-f]{4,6})`)

func keysyms() map[string]rune {
	out := map[string]rune{}
	f, err := os.Open("/usr/include/X11/keysymdef.h")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		if m := symRe.FindStringSubmatch(sc.Text()); m != nil {
			v, _ := strconv.ParseUint(m[2], 16, 32)
			out[m[1]] = rune(v)
		}
	}
	for i := 0x80; i < 0x30000; i++ {
		out[fmt.Sprintf("U%04X", i)] = rune(i)
		out[fmt.Sprintf("U%04x", i)] = rune(i)
	}
	for c := '0'; c <= '9'; c++ {
		out[string(c)] = c
	}
	return out
}

func contains(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}
	return false
}
