package kubectx

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

var rancherCluster = regexp.MustCompile(`^(https?://[^/]+)/k8s/clusters/([^/]+)/?$`)

// IsRancher is whether server is a Rancher cluster proxy, whose kubeconfig Fetch can generate.
func IsRancher(server string) bool { return rancherCluster.MatchString(server) }

// Fetch downloads a kubeconfig: from a URL (token as bearer when set), from a file, or, with no
// source, generated by the Rancher that server points at (token: a Rancher API key).
func Fetch(ctx context.Context, source, server, token string, insecure bool) ([]byte, error) {
	c := &http.Client{Timeout: 30 * time.Second}
	if insecure {
		c.Transport = &http.Transport{Proxy: http.ProxyFromEnvironment, TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
	}
	var req *http.Request
	var err error
	switch {
	case strings.HasPrefix(source, "http://") || strings.HasPrefix(source, "https://"):
		req, err = http.NewRequestWithContext(ctx, http.MethodGet, source, nil)
	case source != "":
		raw, err := os.ReadFile(source)
		if err != nil {
			return nil, err
		}
		return raw, valid(raw)
	default:
		m := rancherCluster.FindStringSubmatch(server)
		if m == nil {
			return nil, fmt.Errorf("%q is not a Rancher cluster address: give the kubeconfig's URL or file", server)
		}
		if token == "" {
			return nil, errors.New("a Rancher server needs an API key (its UI: avatar › Account & API Keys)")
		}
		req, err = http.NewRequestWithContext(ctx, http.MethodPost, m[1]+"/v3/clusters/"+url.PathEscape(m[2])+"?action=generateKubeconfig", nil)
	}
	if err != nil {
		return nil, err
	}
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	raw, err := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	if err != nil {
		return nil, err
	}
	if resp.StatusCode/100 != 2 {
		return nil, fmt.Errorf("%s: %s %s", req.URL.Host, resp.Status, strings.TrimSpace(string(raw[:min(len(raw), 200)])))
	}
	var generated struct {
		Config string `json:"config"`
	}
	if json.Unmarshal(raw, &generated) == nil && generated.Config != "" {
		raw = []byte(generated.Config)
	}
	return raw, valid(raw)
}

func valid(raw []byte) error {
	if !bytes.Contains(raw, []byte("clusters")) || !bytes.Contains(raw, []byte("contexts")) {
		return errors.New("that is not a kubeconfig (no clusters and contexts in it)")
	}
	return nil
}

// Merge adds raw to the user's kubeconfig (the first file of $KUBECONFIG, else ~/.kube/config):
// its entries replace same-named ones, the current context stays, and the old file is kept
// beside it as .rig-backup. It returns the file written and the contexts raw brought.
func Merge(raw []byte) (string, []string, error) {
	dest := filepath.SplitList(os.Getenv("KUBECONFIG"))
	if len(dest) == 0 || dest[0] == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", nil, err
		}
		dest = []string{filepath.Join(home, ".kube", "config")}
	}
	file := dest[0]
	if err := os.MkdirAll(filepath.Dir(file), 0o700); err != nil {
		return "", nil, err
	}
	tmp, err := os.CreateTemp(filepath.Dir(file), ".rig-kubeconfig-*")
	if err != nil {
		return "", nil, err
	}
	defer os.Remove(tmp.Name())
	_, err = tmp.Write(raw)
	if cerr := tmp.Close(); err == nil {
		err = cerr
	}
	if err != nil {
		return "", nil, err
	}
	kubectl := func(kubeconfig string, args ...string) ([]byte, error) {
		cmd := exec.Command("kubectl", append([]string{"config"}, args...)...)
		cmd.Env = append(os.Environ(), "KUBECONFIG="+kubeconfig)
		out, err := cmd.Output()
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			err = fmt.Errorf("kubectl config %s: %s", args[0], strings.TrimSpace(string(ee.Stderr)))
		}
		return out, err
	}
	out, err := kubectl(tmp.Name(), "view", "-o", "json")
	if err != nil {
		return "", nil, err
	}
	var kc kubeconfig
	if err := json.Unmarshal(out, &kc); err != nil {
		return "", nil, err
	}
	var names []string
	for _, c := range kc.Contexts {
		names = append(names, c.Name)
	}
	if _, err := os.Stat(file); errors.Is(err, os.ErrNotExist) {
		return file, names, os.WriteFile(file, raw, 0o600)
	}
	current, _ := kubectl(file, "current-context")
	merged, err := kubectl(tmp.Name()+string(os.PathListSeparator)+file, "view", "--flatten")
	if err != nil {
		return "", nil, err
	}
	old, err := os.ReadFile(file)
	if err != nil {
		return "", nil, err
	}
	if err := os.WriteFile(file+".rig-backup", old, 0o600); err != nil {
		return "", nil, err
	}
	if err := os.WriteFile(file, merged, 0o600); err != nil {
		return "", nil, err
	}
	if c := strings.TrimSpace(string(current)); c != "" {
		_, _ = kubectl(file, "use-context", c)
	}
	return file, names, nil
}
